### ISSUE TITLE
Download time-out expires

### ISSUE THREAD

**Issue by bryanarcega** [aelyo-softworks/ShellBoost-Samples#11]
Hi,

I'm current experiencing time-out expired every time I download file size lager than 50 mb. 
Is the a setting where we can adjust this?

![image](https://user-images.githubusercontent.com/61039800/108896808-54f90800-7650-11eb-87fb-0e8885aa6ff2.png)

Regards,
Bryan Arcega

**Comment by AelyoSoftWorks** [comment]
Hi,

What download are you talking about? With what kind of code/sample do you experience that?

**Comment by bryanarcega** [comment]
I'm using the GetEntryContentAsync to download. All methods have ".ConfigureAwait(false)".
This also occurs in Google Drive Sample

**Comment by bryanarcega** [comment]
Hi,

I need to get the StateSyncEntry.Id from FileSystem.

**Comment by AelyoSoftWorks** [comment]
Hi,

In your `GetEntryContentAsync` code, you must call the `Progress `method of the `ProgressSink `that's passed to the GetEntryContentAsync method to inform the file system of your work. Here is how it should look:

	public Task GetEntryContentAsync(SyncContext context, StateSyncEntry entry, Stream output, SyncGetEntryContentOptions options = null)
	{
		... // some method that supports an event with the downloaded bytes
		return DownloadContentAsync(entry.Id, options.Offset, options.Count, output, options.CancellationToken, (e) =>
		{
			if (entry.Size > 0)
			{
				var ratio = e.BytesDownloaded * 100 / entry.Size;
			        Log(TraceLevel.Verbose, "Progress: " + e.BytesDownloaded + "/" + entry.Size + " (" + ratio + "%)");
			}
			sink.Progress(context, entry.Size, e.BytesDownloaded);
		});
	}


The Cloud Folder Sync sample doesn't exhibit this issue as it's calling this method.

The Google Drive Folder sample did exhibit this issue because the Google API currently does not report progress when calling the ranged method (`DownloadRangeAsync`) but this is specific to Google Drive.

The Google Drive Folder sample code has been modified so the progress is indeed reported.
https://github.com/aelyo-softworks/ShellBoost-Samples/blob/master/ShellBoost.Samples/ShellBoost.Samples.GoogleDriveFolder/Account.cs#L274

Make sure you get the latest version, and you should not see the timeout issue anymore.
