### ISSUE TITLE
[GoogleDriveSample] Interrupted Action Dialog appears when the file is dehydrated (cloud status) and copy-paste on different location

### ISSUE THREAD

**Issue by brian-tumibay** [aelyo-softworks/ShellBoost-Samples#8]
Steps to replicate:
1. Assuming you have successfully added your account to the sample and have file larger than 1GB on the account used
2. Copy the file and paste it on different location that isn't on .../ShellBoost.Samples.GoogleDriveFolder/...
3. Wait until the operation finishes

Expected Result:
- The file will be copied on the target location without prompting any system dialog.

Actual Result:
- System prompts Interrupted Action dialog and asks the user to try again.

Note:
Please refer below for your reference

![image](https://user-images.githubusercontent.com/36059302/105721745-dc732e80-5f5f-11eb-8fa7-85aed95bf218.png)

**Comment by AelyoSoftWorks** [comment]
Hi,

The log you show is about another file (seems it's a PDF file ) than the one with the end-user UI.
The end-user UI message indicates there's a timeout in the fetching of data (google drive => local drive).

We cannot determine the reason why you get a timeout. This can happen for a lot of reasons.

Note we're adding a feature to ShellBoost (including the Google Drive and Cloud Folder Sync samples) to allow hydratation of data in a one shot instead of multiple chunks. It may alleviate that kind of issue.

**Comment by AelyoSoftWorks** [comment]
New version was released. Closing until further notice.
